version: "3.9"
services:
  go-gemini-telegram-bot:
    image: ghcr.io/hkint/go-gemini-telegram-bot:latest
    container_name: go-gemini-telegram-bot
    restart: always
    environment:
      TZ: Asia/Shanghai
      BOT_TOKEN: 
      GEMINI_API_KEY:
      ALLOWED_USERS:  # Optional, if you want to only allow certain users to access the pkg
      BOT_DEBUG_MODE: true
